CONFIG = {
    "dataset": "movielens",
    "data_dir": "./generative_ranking/data/ml-1m/",
    "model_name": "all",
    "device": "cpu",
    "seed": 2026,
    "save_dir": "./generative_ranking/outputs/movielens/",
    "dataset_params": {
        "max_seq_len": 50,
    },
    "training": {
        "epoch": 5,
        "learning_rate": 1e-3,
        "batch_size": 1024,
        "weight_decay": 1e-5,
        "earlystop_patience": 3,
    },
    "dcn_v2": {
        "n_cross_layers": 3,
        "mlp_params": {"dims": [256, 128], "dropout": 0.2, "activation": "relu"},
    },
    "rankmixer": {
        "d_model": 128,
        "num_layers": 2,
        "num_tokens": 4,
        "seq_pool_modes": ["mean", "target"],
        "use_moe": True,
        "moe_experts": 4,
        "moe_l1_coef": 1e-4,
        "moe_sparsity_ratio": 0.5,
        "moe_use_dtsi": True,
        "moe_routing_type": "relu_dtsi",
        "input_dropout": 0.1,
        "token_mixing_dropout": 0.1,
        "ffn_dropout": 0.1,
        "head_dropout": 0.1,
    },
}